# -- Replica count.
replicaCount: 1

# -- Image configuration.
image:
  # -- Image repository.
  repository: bitnami/kubectl
  # -- Pull policy image
  pullPolicy: IfNotPresent
  # -- Image tag.
  tag: "1.32"

# -- Reference to one or more secrets to be used when pulling images.
#
# For example:
#  imagePullSecrets:
#    - name: "image-pull-secret"
imagePullSecrets: []
# -- Replaces the name of the chart in the Chart.yaml file, when this is used to construct Kubernetes object names. Reference: https://stackoverflow.com/questions/63838705/what-is-the-difference-between-fullnameoverride-and-nameoverride-in-helm
nameOverride: ""
# -- Completely replaces the rest of the logic in the template. Reference: https://stackoverflow.com/questions/63838705/what-is-the-difference-between-fullnameoverride-and-nameoverride-in-helm
fullnameOverride: ""

# -- Time to wait pod delete. Reference: https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-terminating-with-grace
terminationGracePeriodSeconds: 30

# -- Watchdog configuration.
watchdog:
  # -- Interval in seconds to check pods.
  checkInterval: 120
  # -- List of error pod statuses.
  errorStatuses: "CrashLoopBackOff|Error|OOMKilled"
  # -- List of namespaces to monitor. If empty, monitor all.
  namespaces: []
    #- "namespace1"
    #- "namespace2"
    #- "namespace3"
  # -- List of namespaces that should be ignored
  excludeNamespaces:
    - "default"
    - "helm-watchdog-pod-delete"
    - "kube-system"
    - "kube-node-lease"
    - "kube-public"
    - "gke-managed-cim"
    - "gke-managed-filestorecsi"
    - "gke-managed-system"
    - "gmp-public"
    - "gmp-system"
  # -- Grant the same permissions to watchdog pod. More info: https://kubernetes.io/docs/reference/access-authn-authz/rbac/
  clusterRole:
    rules:
      - apiGroups: [""]
        resources: ["pods"]
        verbs: ["get", "list", "delete"]
      - apiGroups: [""]
        resources: ["namespaces"]
        verbs: ["get", "list"]

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Automatically mount a ServiceAccount's API credentials?
  automount: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# -- Annotations to add to the pods
podAnnotations: {}

# -- Labels to add to the pod
podLabels: {}

# -- Pod security configurations
podSecurityContext: {}
  # fsGroup: 2000

# -- Security Context configurations. Reference: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# -- Resource requests and limits for the pod
resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 10Mi

#livenessProbe: {}
#readinessProbe: {}

# -- Additional volumes on the output Deployment definition.
volumes:
  - name: kube-api-access
    projected:
      sources:
        - serviceAccountToken:
            path: token
        - configMap:
            name: kube-root-ca.crt
            items:
              - key: ca.crt
                path: ca.crt

# -- Additional volumeMounts on the output Deployment definition.
volumeMounts:
  - name: kube-api-access
    mountPath: /var/run/secrets/kubernetes.io/serviceaccount
    readOnly: true

# -- nodeSelector configurations. Reference: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
nodeSelector: {}

# -- Tolerations configurations. Reference: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
tolerations: []

# -- Affinity configurations. Reference: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
affinity: {}
