name: "Deploy pipeline"

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      region:
        type: string
        required: true
    secrets:
      KUBECONFIG:
        required: true
      GLOBAL_KUBECONFIG:
        required: true
    outputs:
      HERONAME:
        required: false
      GLOBAL_HERONAME:
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure environment variables
        run: |
          mkdir ~/.kube/
          echo "${{ secrets.KUBECONFIG }}" >> ~/.kube/config
          echo "${{ secrets.GLOBAL_KUBECONFIG }}" >> ~/.kube/config
          cat ~/.kube/config
          echo "HERONAME=${{ env.HERONAME }}"
          echo "GLOBAL_HERONAME=${{ env.GLOBAL_HERONAME }}"
          echo "ENVIRONMENT=${{ inputs.environment }}"
          echo "REGION=${{ inputs.region }}"
