# References:
# https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows
# https://www.bitovi.com/blog/github-action-helm-charts-eks
# https://medium.com/@phil16terpasetheo/deploy-helm-chart-to-eks-cluster-using-cicd-pipeline-with-github-actions-4ed098da8dab
# https://github.com/marketplace/actions/deploy-helm-chart-to-aws-eks-cluster
# https://github.com/orgs/community/discussions/26671
# https://docs.github.com/en/actions/sharing-automations/reusing-workflows#limitations
# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables
# https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions
# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-an-environment-variable
# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#env-context
# https://docs.github.com/en/actions/sharing-automations/reusing-workflows#using-outputs-from-a-reusable-workflow

name: "Main pipeline"

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to helm'
        required: true
        default: 'install'
        type: choice
        options:
        - install
        - uninstall
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy_undeploy_helm_watchdog_prod:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout Github Repo
      uses: actions/checkout@v4

    # https://artifacthub.io/packages/helm/helm-watchdog-pod-delete/helm-watchdog-pod-delete 
    - name: Deploy helm-watchdog-pod-delete
      uses: bitovi/github-actions-deploy-eks-helm@v1.2.12
      with:
        aws-access-key-id: ${{ secrets.PRD_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.PRD_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.PRD_AWS_REGION }}
        cluster-name: ${{ secrets.PRD_CLUSTER1_NAME }}
        action: ${{ github.event.inputs.action || 'install' }}
        dry-run: false
        config-files: prod/helm-watchdog-pod-delete/values.yaml
        # Extra environment variables if the supported by helm chart
        #values: extraEnvVars.KEY1=value1,extraEnvVars.KEY2=value2
        chart-path: helm-watchdog-pod-delete/helm-watchdog-pod-delete
        version: 0.2.0
        namespace: helm-watchdog-pod-delete
        timeout: 900s
        helm-wait: true
        create-namespace: true
        name: helm-watchdog-pod-delete
        chart-repository: https://aeciopires.github.io/helm-watchdog-pod-delete


    - name: Deploy nginx
      uses: bitovi/github-actions-deploy-eks-helm@v1.2.12
      with:
        aws-access-key-id: ${{ secrets.PRD_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.PRD_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.PRD_AWS_REGION }}
        cluster-name: ${{ secrets.PRD_CLUSTER1_NAME }}
        action: ${{ github.event.inputs.action || 'install' }}
        dry-run: false
        # Custom values files if necessary
        #config-files: prod/nginx/values.yaml
        # Extra environment variables if the supported by helm chart
        values: controller.env.KEY1=value1,controller.env.KEY2=value2,image.tag=4.0.1-alpine
        chart-path: nginx/charts/nginx-ingress
        version: 2.0.1
        namespace: nginx
        timeout: 900s
        helm-wait: true
        create-namespace: true
        name: nginx
        chart-repository: oci://ghcr.io
